### ISSUE TITLE
Refactor, polish and document gama-server and its API

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#1]
**Is your request related to a problem? Please describe.**
Currently gama-server GUI and gama-server headless are not fully compatible, a client working for one could not be completely working for the other. In addition to this, some parts are just proof of concepts that lack some polish, and are not documented yet.

**Describe the improvement you'd like**
Here are the problems to tackle:
- [x] in headless we need to use exp_id but the gui only returns the experiment name
- [x] if using exp_id in gui, gama will try to resolve it even though it is meant to work only with the current experiment
- [ ] the messages of type simulation status are only sent in the case of gui use
- [ ] The use of GS in GUI is undocumented (see [this issue](https://github.com/gama-platform/gama-platform.github.io/issues/198))
- [ ] The error message RuntimeError is not used anymore
- [ ] There's currently no documentation on simulation status, what should be documented is (see [this issue](https://github.com/gama-platform/gama-platform.github.io/issues/201)):
    - [ ] the list of all the different status and their meaning
    - [ ] the general explanation of how they work: how to subscribe to them? Can multiple clients get the same messages? What format are they following
- [ ] being able to unsubscribe from status messages as described in a previous issue(#15)
- [ ] being able to query for the current simulation status as described in [this comment](https://github.com/gama-platform/new.gama/issues/15)
- [x] The compilation errors message is vague and should contain more information (#172)
- [ ] in gui mode the server options are not taken into account, every data is sent to the client regardless of the options set in the load function call (runtime, console, inform etc.) (#394)
- [ ] refactor the code to compile models that is common between the `load` and the `describe` commands (see this [PR](https://github.com/gama-platform/gama/pull/404)). 

**Additional context**
This is this repository's first issue 🥳

**Comment by Vezonne** [comment]
This kind of improvement for the gama_gymnasium package would be really helpful. Moreover, the behavior of the status messages is not the same in headless and in gui. In gui there are unexpected status messages at the beginning of the simulation that are not present in headless.
