### ISSUE TITLE
Tracker: GamaFile framework 

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1362]
Hi,

The file infrastructure has been considerable improved since GAMA 1.6.1, but we need to do more and better. I've counted at least 8 issues that directly relate to this infrastructure (#1164, on adding an image type; #1076 on saving geometries in shape files directly; #1352 on saving agent attributes in CSV files; #1252 on reading GML files; #1253 on GeoTiff files; #1261 on ontology files (KML); #761 on 3D formats; #762 on extending and generalizing the framework with database access. 

GamaFile and its subclasses have provided a great way, so far, to load and manipulate various kinds of data used as an input for model. The first task is to continue completing this so as to address the needs in terms of data expressed in these different issues.

The second task is to slowly enhance the current `save` statement so that it allows to save files that can be declared, manipulated, changed, etc. by the modeler. This requires to implement only one method (but a huge one !) in GamaFiles : `flushBuffer()`. Something like this would definitely ease tasks such as the one described in #1352.

The third task is to generalize the current framework to access any kind of data (more on this is described in #762). It is the more complex to do, but not out of reach for GAMA 1.7. 

One fourth task, linked with the UI, is to facilitate the creation of (or linkage with) viewers for the various kinds of files - it is already done for GAML files (of course :) ), SVG/HTML files, CSV files, shape files and most image formats. 

What do @gama-platform/core and @gama-platform/committers think about it ? 

For the moment, this tracker then covers: 

- [ ] #1164, add an `image` type to GAML
- [x] #1076, saving geometries (not agents) to shape files
- [x] #1352, saving agents into CSV files (see also #2452)
- [ ] #2452, asking for the same facility in save
- [x] #1252, on reading GML files
- [x] #1253, on GeoTiff files
- [x] #1261; on KML files
- [x] #761, on 3D formats
- [ ] #762, on linking files and database access (_a la_ Geotools)
- [x] #1494, document the file constructors (see also #2399)
- [ ] #2260, about incorporating graphs read/write in the GamaFile framework
- [ ] #2109, including GDAL for loading various raster formats
- [x] #2344, describing a bug when saving georeferenced png of jpeg images

**Comment by AlexisDrogoul** [comment]
GamaFiles can now be passed an URL ( #2005 ) and will automatically try to fetch its contents in a temp file. This default behavior works for simple file types, but won't for others with additional support files. This adds a new task to this issue: redefining automaticallyFetchFromURL() and fetchFromURL() in subclasses, and also taking into account that the `path` attribute can now be null or empty (and in that case, replaced by the `url` attribute).

**Comment by AlexisDrogoul** [comment]
The `save` statement now accepts a file for its first argument ( #1900 ). It then automatically calls the `save()` method of GamaFiles (passing an additional map of parameters if necessary), which in turn (after some verifications) calls `fillBuffer()` (which now accepts an IScope parameter). So everything is in place to allow to write, for instance: 

```
map<string, unknown> mm <- ...; // fill it
save json_file("saved.json", mm);
```

or to make copies:

```
save shape_file("copy.shp", shape_file("original.shp").contents);
```

Except that the fillBuffer method is only written for one class for the moment (GamaJsonFile). It won't make errors for the others, but won't do anything either...

**Comment by AlexisDrogoul** [comment]
Summary of the additions to the GamaFile framework to handle urgently:

- [ ] redefine `automaticallyFetchFromURL()` and `fetchFromURL()` if necessary and take into account the fact that the `path` can now be null or empty (replaced in that case by `url`)

- [ ] redefine `fillBuffer()` and/or `save()` (in case parameters need to be read).

**Comment by AlexisDrogoul** [comment]
Added issue #1494 under this general tracker ("Document the xxx_file constructors").

**Comment by AlexisDrogoul** [comment]
Closing for now on.
