### ISSUE TITLE
Issue tracker related to diffuse_light / normal computation

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1716]
Hi,

We have a number of issues popping up related to diffuse_light / normal computation and I propose to use this bug tracker to group them (so that, since they are probably strongly related, they are not treated completely separately.

- [x] Issue #1712 on the problem of complex shapes and diffuse_light (apparently not affecting the shapes in the same way).
- [x] Issue #1702 on the problem of diffuse_light not affecting the shapes and the images in the same way (probably something about the normal again)
- [ ] Issue #1710 on the problem of the position of the diffuse_light and how it affects 2D shapes.
- [x] Issue #1711 on the problem of defining diffuse_light

In addition, we already had #1701 (reflection not accurate), #1691 (changing the light for the referentials), #1680 (problems of colors -- some of them related to light if I recall correctly -- see also #828, which was an earlier iteration of the same bug, supposedly fixed but actually not...). Since some of the problems may have arised from fixing them, I think it's necessary to track them too.

**Comment by AlexisDrogoul** [comment]
Just to add a quick note to this: the color rendering with the current diffuse_light is not yet on par with Java2D displays (which I consider as being "accurate"). See for example the "Moving Agents" model in User Interaction (Features), where I have put side by side the same display in Java2D and OpenGL. The circle is completely faded in OpenGL.

**Comment by mazarsju** [comment]
In "Moving Agents", if we replace the geometry of the "zone" to a square (instead of a circle), the colors appear fine. It is definitely a problem of norm computation for a circle, I'll investigate.

**Comment by mazarsju** [comment]
Here is what I propose for the lights :

- The statement "display" will only have the "ambient_light" facet. By default, the value of ambient_light is "50,50,50,255".
- Inside the display, we can use a new statement "light". This statement light will have the following facets :
 - **id** : a number from 0 to 7 to specify which light we are using.
 - active_when (optional) : a boolean expression telling if you want this light to be switch on or not. (default value : true)
 - color (optional) : an int / rgb / rgba value to specify the color and the intensity of the light. (default value : (255,255,255,255) ).
 - type (optional but warning raised if not specified) : a value among [direction, point, spot] to specify what type of light do you want. (default value : point)
 - position (optional, only for "point" and "spot" type) : the position of the light. (default value : center of the world (in (x,y)), above the world)
 - direction (optional, only for "direction" and "spot" type) : the direction of the light. (default value : (1,0,1))
 - cone_angle (optional, only for "spot" type) : the angle of the cone of light in degree. (default value : 10)
 - linear_attenuation (optional, only for "point" and "spot" type) : the linear attenuation of the light (default value : 0)
 - quadratic_attenuation (optional, only for "point" and "spot" type) : the quadratic attenuation of the light (default value : 0)
 - show_light (optional) : boolean, add a representation of the light in the world if turned to true. "point" and "spot" lights are displayed in their position, with their color. "direction" lights are displayed as a vector in the corner of the screen (default value : false) <-- this point may be a bit complicated to implement, it will be done at the end. The representation of the "direction" light can be mixed with the enhancement of the interactive referential in the corner (see #1703).

All those "lights" are more precisely "diffusion lights". 
By default, an opengl display has an ambient light, and the light number 0 activated (the other are not activated). This light has the type "direction", the direction is the by default (1,1,4) (this is the current direction computed if you have world.shape.width = world.shape.height). The color of this light has the value (110,110,110,255), which is the value needed to have the same colors for 2D shapes (in the plan (x,y)) in opengl and java2D displays, for this direction.

All those changes will be documented (of course) in a recipe.

**Comment by mazarsju** [comment]
I implemented a solution close to the one I described above. It's working fine, and resolve most of the issues described above.
Notice that the [documentation ](https://github.com/gama-platform/gama/wiki/ManipulateLight) has been updated also.

One problem remain : 
The light is not correct when drawing shapes with the facet "rotate" : indeed, the investigations I made lead me to the fact that when a rotation is done (through a "glRotate"), we have to rotate manually the light in the opposite direction to lighten the right face. This is not possible in the JTSDrawer : this part of the code is placed between a "glNewList" and a "glEndList", and we have no access to the light position in this part of the code.

**Comment by agrignard** [comment]
One good model to see easily the difference rendering using rotate and rotated_by.

model complexobjectloading   

global {
	init { 
		create ComplexObjectRotate3D number:1{
			set location<-{50,50};
		}
	}  
} 

species ComplexObjectRotate3D{
	aspect objXYZRotate {
		draw cube(25) color:rgb('blue') rotate:(time*10 ::{1,1,1}) ;
	}
	aspect objXYZRotatedBy {
		draw cube(25) rotated_by(time*10,{1,1,1})   at:{location.x,location.y,10} color:rgb('blue') ;
	}
}	


experiment DisplayRotate3D  type: gui {
	output {
		display ComplexObjectXYZ1 type:opengl   background:°orange{
			species ComplexObjectRotate3D aspect:objXYZRotate;					
		}
		display ComplexObjectXYZ2 type:opengl   background:°orange{
			species ComplexObjectRotate3D aspect:objXYZRotatedBy;					
		}
	}
}

**Comment by agrignard** [comment]
[Objects Rotate.txt](https://github.com/gama-platform/gama/files/270344/Objects.Rotate.txt)

**Comment by AlexisDrogoul** [comment]
I would suggest to open a new issue for the rotation, as most of the problems have been fixed here (or did I miss something ?)

**Comment by mazarsju** [comment]
yes indeed. I close this one and open #1861
