### ISSUE TITLE
Tracker: Camera issues

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1878]
Several issues are still floating around regarding the cameras and their definition, management, etc. 
This issue tracker is meant to group them into one coherent set in order to address them all in a global way. They will be closed for the sake of clarity, but their actual resolution needs to be indicated here (by checking the box).

Most central issue:
- [ ] #579 proposes to define the position of the camera using a specific statement (`camera`) and predefined cameras (reopened in reference to https://github.com/gama-platform/gama/issues/2757#issuecomment-498885620 )

Improvement of existing behaviors
- [x] ~~#1414 requests improvement of grid display rendering when the camera is in the XY plan~~
- [ ] #995 proposes to reintroduce/improve the isometric perspective (could be defined in the definition)
- [x] ~~#1618 proposes to merge FreeFly and ArcBall cameras (will not be done)~~
- [ ] #807 proposes to improve the focus 

Addition of new capabilities:
- [ ] #868 proposes to add a "follow" behavior (using a repeated focus) (could be specified in the definition)
- [ ] #1802 proposes to add a miniature global view linked with the camera position (could be specified in the definition as well)
- [ ] #1159 proposes to synchronize the cameras in 2 different displays (could be maybe done in using the same name in the definition ? or to add a facet `synchronized_with` ? )
- [x] ~~#1856 proposes to specify, additionally, the field of view in this definition (done)~~
- [ ] #2640 proposes to pass one of the camera presets to the display
- [ ] #2694 proposes to revert the Y axis of the camera in GAML and in the GUI
- [ ] #2742 Proposes to add a model dedicated to camera position
- [ ] #2744 Describes a bug where the world is upside down after a camera change of height
- [ ] #2746 Describes a bug about the usage of the facet focus
- [ ] #2757 proposes an enhancement to have an initial position of the camera and then navigate in a model

**Comment by agrignard** [comment]
Any update on this "big" issue? 

One thing related to gama-platform/gama#579, one very cool feature could be to be able to save  the camera settings once you find you're right field of view (by pressing on a special button) in txt file and then being able to reset the camera position from this text file at the initialization of a simulation.

**Comment by agrignard** [comment]
Maybe the best option would be to enhance the "bottom overlay" that already display the position of the cam, I think if it displays also the look_pos and upVector is does the trick. it's maybe a lot of information for the user but anyway this is an information layer.

Actually in LayeredDisplayView '''getOverlayZoomInfo()''' the only information we have is '''ds.getCameraPosition()''' I would be in favor to modify that in order to get (and display) pos,lookpos and upvector

**Comment by agrignard** [comment]
I think it's more or less here with this commit
https://github.com/gama-platform/gama/commit/5b26f83941b615374c588555e287360ace6dbcc9

the only thing I miss now is that the overlay size is a bit too short so it's not possible to display the hole information. 

I tried it and I think (at least for my case) it's great, you can spend time to choose a good angle and then being able to redefine it using camera_pos: {} camera_look_pos: {} camera_up_vector:{}

In the ideal world it should use the camera statement instead
