### ISSUE TITLE
Tracker: OpenGL "shader" pipeline

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2134]
The new implementation of the OpenGL pipeline, based on GLSL, is not maintained for the moment. Several issues (some listed here, like #2036, #2012, #2049, some not, like the rotation of 2,5D shapes) however plague it and it is not advised to use it. For this reason, I'm closing temporarily the related issues and list them here, as a reminder of things to pay attention to when it will be "reactivated": 

- [ ] #2036 Problems with the display of grids
- [ ] #2012 Interior rings not displayed
- [ ] #2049 Memory usage of the architecture

Most of the functionalities of this pipeline are however available (include keystoning, with the use of a shader) in the fixed ("regular") OpenGL pipeline, except materials, which are not taken into account.

**Comment by AlexisDrogoul** [comment]
This is no longer available in GAMA. Will probably be completely rewritten from scratch at some point, either in a web client (see https://github.com/gama-platform/gama.client) or using a full-fledged library like https://github.com/jzy3d/jzy3d-api
