### ISSUE TITLE
Tracker: 3D geometries Issues

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2206]
A recurrent request pops up in the issues about the possibility to develop models in 3D (and to benefit from the same capabilities than the ones available in 2D: query operators, spatial transformations, etc.). While it is clearly out of reach of GAMA right now (because we use JTS as the geometrical and spatial framework of the platform), it might become one of the goals for GAMA 1.8. This tracker is intended to keep track of the issues declared so far on this aspect. 

- [ ] Adapting the `moving3D` skill to accept 3D bounds in #2198 
- [ ] Refactoring the `moving3D`skill (see #2581)
- [ ] Returning 3D points for `any_point_in` in #2199 and for `points_on` in #2054 
- [ ] Adapting query operators (like `inside`) in #1229 
- [ ] Generalising 3D geometries in #765

**Comment by AlexisDrogoul** [comment]
Closing it now
