### ISSUE TITLE
Tracker: OpenGL rendering issues

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2209]
A number of issues deal with the rendering quality of OpenGL displays. I have decided to regroup them here in order, one day, to try to deal with them systematically once we revise the rendering architecture. 

- [x] ~~#2174 describes a degradation of the rendering quality after a keystone transformation~~
- [x] ~~#2159 describes a problem of flickering (probably due to z-fighting) when moving the mouse over the screen with `trace` on.~~
- [x] ~~#2288 describes a problem where the overlay layer position is not completely fixed in OpenGL~~
- [x] ~~#2276 (after #828) describes a problem of colours fading (probably due to light)~~
- [x] ~~#2380 points at the bad rendering of large images used as background on OpenGL displays (improved but still worse than Java2D)~~
- [x]  ~~#1678 tries to understand how to render OpenGL displays in headless mode~~
- [x] ~~#2127 (after #1718) asks for increasing the quality of line drawing~~ 
- [ ] #2208 exposes a problem with transparent colours and the drawing of built-in shapes (like cubes)
- [ ] #2279 describes a wrong behaviour of the trace when layers move in the z dimension
- [ ] #2322 describes a problem of shading with Obj files
- [ ] #2486 describes a problem (blank screen) when the size of the model environment is too small (<1#mm).
- [ ] #2488 describes a bug (rotation about an axis which is not perpendicular to XY plan) when both `rotation:` and `size:` are used to draw a sphere or a cylinder
- [ ] #2679 shows that polygons with holes in 3D do not display their internal faces
- [ ] #2759 raises an issue with the display of textures on rotated geometries
- [ ] #2754 raises an issue with the display of textures for specific `camera_pos` values
- [x] ~~#2923 grid facets (at least elevation, grayscale and triangulation) does not work on windows~~

Feel free to add new issues about quality rendering in OpenGL and reference them here.

**Comment by AlexisDrogoul** [comment]
gama-platform/gama#2159 is probably related to gama-platform/gama#2224.

**Comment by AlexisDrogoul** [comment]
gama-platform/gama#2159 is solved by the fix to gama-platform/gama#2224 .
