### ISSUE TITLE
Tracker: Charts issues

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2210]
Charts are still a complex part of the displays in GAMA, especially because they are not updated very regularly ( @pcaillou  :) ). I open this issue to track the problems and enhancements related to charts. Feel free to add new ones (by editing the issue or adding a comment).

- [ ] #1932 asks for some facets to be dynamic
- [ ] #2096 asks for the possibility to define logarithmic scales
- [ ] #1014 asks for dual Y axes

**Comment by pcaillou** [comment]
solve 3 issues (second axis only for series/xy, not for categoryplot)
