### ISSUE TITLE
Tracker: network plugin issues

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2449]
This tracker to group the issues related to the network plugin (developed and maintained mainly by @gnoubi and @dphilippon). The issues are listed here, please tick them when they are fixed.

- [x] #2364 Problem when running a MQTT connection w/o server
- [x] #2365 UDP connection dropping 
- [x] #2361 No documentation is available 

Feel free to edit this meta-issue by adding new individual issues when they appear.

**Comment by AlexisDrogoul** [comment]
@gnoubi, @dphilippon any chance you can test / review these bugs for the 1.8 release ? Documentation is crucial, btw (#2361).

**Comment by benoitgaudou** [comment]
It tried to fix issue #2365 (UDP connection dropping), by using the TCP infrastructure for the UDP protocol.
If it works well, this plugin needs a refactoring as the classes for the UDP and TCP protocols become more and more similar ... 

I have tried only on the basic Helloworld of the model library.

@agrignard : could you try on more advanced models ? 

Benoit

**Comment by benoitgaudou** [comment]
I addressed all the issues... but some tests by some other people could be very usefull.

**Comment by agrignard** [comment]
@benoitgaudou what do you mean by more "advanced models"?

I can maybe illustrate the kind of using I am doing using TCP with other project (e.g with processing)

Personnaly I have always thought that the network plugin was never really working so I didn't even start to send UDP to a GAMA model but I can restart to use it if it works

**Comment by benoitgaudou** [comment]
Hi,

For the moment, I just made the helloworld from the model library work.
So anything more complex than that ...
In particular it could be nice to try sending messages from another
application to gama using upd.

Concerning the net work plugin, Nico uses it for littosim or marrak’air,
but mainly with mqtt.

Cheers

Benoit

Le sam. 25 août 2018 à 21:37, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by gnoubi** [comment]
Hi,

I am going to test the plug-in next week. 

I have a response for the connection loose. Udp and tcp do not reconnect automatically when the connection is lost. 

Mqtt is based on tcp or udp and manage this problem. It is one of the reasons that I advise the mqtt protocol. 

I think, udp and tcp should be used for exotic case study, not for the major use of networking.

Nico


Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906

**Comment by AlexisDrogoul** [comment]
OK. So I close this tracker for the moment. Please open more focused issues if tests reveal problems.

**Comment by benoitgaudou** [comment]
Just to add that all the issue of the tracter are « solved » if we can
say...
But I noticed yesterday evening that my implémentation of the UDP protocol
are totally wrong...

I am working on it communicating with Nico and Arnaud.

Benoit

Le mar. 28 août 2018 à 10:37, Alexis Drogoul <notifications@github.com> a
écrit :

**Comment by benoitgaudou** [comment]
A more correct implementation of UDP communication has just been committed.
So this tracker can now be considered as close in a clean way:-)

**Comment by hqnghi88** [comment]
Dear Benoit, Nico,
Thank you so much for the patch of tcp and udp. Sorry i did not have time for it, i am struggling with gamaweb in couple of weeks. 
Just asking why the udp cannot work for the gama-gama (i read in your commit message limited to communication between GAMA and other external)?

**Comment by benoitgaudou** [comment]
Hi Nghi,

So the fact that UDP cannot work for the Gama - Gama communication is due
to a mix of implementation choices, technical possibilities and limitations
of the UDP and my own knowledge about this protocol :-)

As far as I am aware, the UDP does not have a connected mode, it does not
ensure the reception of the messages and so on. Contrarily to the TCP
protocol, where a connection can be created and maintained, and where when
a message is sent, the protocol ensures that it will be received.
Finally the UDP seems to be used to send some amount of data, without any
check of the reception.

As GAMA can already manage communication between GAMA Agents using the TCP
protocol, it seems to me useless to manage a second protocol to do exactly
the same things :-)
So I considered that the UDP could be used for another purpose :
communicate with other applications that send small amount of data (e.g.
location of the mouse ... ) to / from GAMA.
In addition, the only use case of the UDP protocol was to be used to
communicate with Process, sending/receiving coordinates of a mouse.

As a consequence, I also simplified the message sent using the UDP : it it
not a GAMA message, but simply the content of this message.

Hope it clarifies to point. All of that can of course be the subject of
further discussions.

Cheers

benoit

Le ven. 31 août 2018 à 17:45, HUYNH Quang-Nghi <notifications@github.com> a
écrit :
