### ISSUE TITLE
Tracker: Headless and OpenMole issues

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2453]
Several issues related to the headless mode (incl. its use in OpenMole) are sticking in the Issues list. This tracker lists them, hoping they will find a solution soon ! Feel free to modify it to add new ones.

- [x] #2311, where compilation errors do not seem to vanish between two compilations
- [ ] #2190, where EPSG codes cannot be read in headless mode
- [x] #2137, where a variable cannot be read at the end of an headless simulation in OpenMole (see if it hasn't been solved by #2426)
- [x] #1821, which reviews all the errors produced by the Models Library models in headless
- [x] #2554, which describes a runtime error raised by FileUtils only in headless mode
- [x] #2608, which describes an error when trying to load an online file in headless mode
- [x] #2602, which describes an error when using multiples model files in headless mode
- [x] #2588, which asks for a way to set the sizes of snapshots in headless mode
- [x] #2583, which describes another error when using multiple model files (main model run twice)

**Comment by AlexisDrogoul** [comment]
@gnoubi, any chance you can test / review these bugs for the 1.8 release ?

**Comment by hqnghi88** [comment]
check #1821 on ubuntu, seem the headless importation is the root cause of several issue which is solved.
~/git/gama/ummisco.gama.product/target/products/ummisco.gama.application.product/linux/gtk/x86_64/headless$ java  -cp ../plugins/org.eclipse.equinox.launcher*.jar -Xms512m -Xmx2048m  -Djava.awt.headless=true org.eclipse.core.launcher.Main  -application msi.gama.headless.id4 -data .work2 -v -validate 

359 GAMA models compiled in built-in library and plugins. 0 compilation errors found

**Comment by AlexisDrogoul** [comment]
I close this tracker, as #2190, not yet fixed, is probably due to the way OpenMole loads libraries.
