### ISSUE TITLE
Tracker: Graphical requests for enhancement

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2728]
Several requests for enhancing the graphical subsystem of GAMA have been made. This tracker regroups the ones which have not been, yet, answered.

- [ ] #2600 Asks for a "drape effect" regarding geometries displayed on DEM
- [ ] #2537 Asks for a built-in icon representing GAMA
- [ ] #2176 Asks for the addition of the `rotate` facet at the layer level.
- [ ] #2038 Asks for the design of an 'aspect library'
- [ ] #2119 Asks for the possibility to fill shapes with gradients 
- [ ] #2761 Asks for rotating displays in the 3 dimensions
